var origin = window.location.origin;
var pathname = window.location.pathname;    
var imageAbs = origin + window.imageRel;
var urlAbs = origin + pathname;
var bodyStyles = getComputedStyle(window.document.body);
var backgroundColor = bodyStyles.getPropertyValue('background-color');
var elementTitles = document.querySelectorAll('.usesTitle');
elementTitles.forEach(function(element) {element.innerText = window.title});
var metaDescription = document.querySelector('[name="description"]');
metaDescription.setAttribute('content', window.description);
var elementImageRel = document.querySelector('.usesImageRel');
elementImageRel.src = window.imageRel;
var elementDate = document.querySelector('.usesDate');
elementDate.innerText = window.date;
var openGraphTitle = document.querySelector('[property="og:title"]');
openGraphTitle.setAttribute('content', window.title);
var openGraphImage = document.querySelector('[property="og:image"]');
openGraphImage.setAttribute('content', imageAbs);
var openGraphUrl = document.querySelector('[property="og:url"]');
openGraphUrl.setAttribute('content', urlAbs);
var metaThemeColor = document.querySelector('meta[name="theme-color"]');
metaThemeColor.setAttribute('content', backgroundColor);